# Generated by Django 2.1.5 on 2019-01-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultConf',
            fields=[
                ('imageId', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('creationDate', models.DateField()),
                ('url', models.CharField(max_length=1000)),
                ('expireDate', models.IntegerField()),
                ('hostingType', models.CharField(choices=[('W', 'Website'), ('V', 'Video'), ('I', 'Image'), ('O', 'Other')], max_length=1)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
